version: '3.8'

services:
  cine-api:
    build: .
    container_name: cineplus-api
    ports:
      - "3526:3526"  
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://cineplus-db:27017/cineplus  # Corrigido para usar a porta 27017
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: cineplus-db
    ports:
      - "27018:27017"  # Mapeia a porta 27017 do container para a porta 27018 do host
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
